export const languages = {
  pl: '🇵🇱 PL', en: '🇬🇧 EN', de: '🇩🇪 DE', es: '🇪🇸 ES', it: '🇮🇹 IT',
  fr: '🇫🇷 FR', uk: '🇺🇦 UA', cs: '🇨🇿 CS', sk: '🇸🇰 SK', hu: '🇭🇺 HU'
} as const
export type Language = keyof typeof languages

const pl = {
  tagline: 'LEĆ W RYTMIE SŁOŃCA', title: 'Twój prawdziwy', titleAccent: 'czas słoneczny',
  subtitle: 'Sprawdź naturalny rytm dnia i zaplanuj lot, gdy termika pracuje najlepiej.',
  solarTime: 'CZAS SŁONECZNY', localTime: 'czas lokalny', solarNoon: 'POŁUDNIE SŁONECZNE',
  ground: 'najsilniejsze nagrzewanie ziemi', thermal: 'SZCZYT TERMIKI', air: 'najsilniejsze nagrzewanie powietrza',
  distance: '1 MINUTA SŁONECZNA', along: 'wzdłuż równoleżnika', location: 'TWOJA LOKALIZACJA',
  useLocation: 'Użyj mojej lokalizacji', locating: 'Ustalam pozycję…', or: 'LUB WPISZ MIEJSCE',
  placeholder: 'np. Bassano del Grappa', search: 'Szukaj', searchHint: 'Wpisz miasto, region lub adres i zatwierdź.',
  noResults: 'Nie znaleziono takiego miejsca.', errorSearch: 'Nie udało się pobrać wyników. Spróbuj ponownie.',
  denied: 'Nie udało się pobrać lokalizacji. Wpisz miejsce ręcznie.', select: 'Wybierz lokalizację',
  timezone: 'Strefa', coords: 'Współrzędne', info: 'Wskazania są orientacyjne. Warunki termiczne zależą też od pogody, terenu i pory roku.',
  footer: 'Dane miejsc: © OpenStreetMap contributors', km: 'km', calculating: 'Czekam na lokalizację'
}

export type Dictionary = typeof pl
const dictionaries: Record<Language, Dictionary> = {
  pl,
  en: { ...pl, tagline:'FLY WITH THE SUN', title:'Your true', titleAccent:'solar time', subtitle:'Follow the natural rhythm of the day and plan your flight when thermals work best.', solarTime:'SOLAR TIME', localTime:'local time', solarNoon:'SOLAR NOON', ground:'strongest ground heating', thermal:'THERMAL PEAK', air:'strongest air heating', distance:'1 SOLAR MINUTE', along:'along this latitude', location:'YOUR LOCATION', useLocation:'Use my location', locating:'Locating…', or:'OR ENTER A PLACE', placeholder:'e.g. Bassano del Grappa', search:'Search', searchHint:'Enter a city, region or address and submit.', noResults:'No place found.', errorSearch:'Could not fetch results. Try again.', denied:'Could not get your location. Enter a place manually.', select:'Choose a location', timezone:'Time zone', coords:'Coordinates', info:'Times are indicative. Thermal conditions also depend on weather, terrain and season.', footer:'Place data: © OpenStreetMap contributors', km:'km', calculating:'Waiting for location' },
  de: { ...pl, tagline:'FLIEG MIT DER SONNE', title:'Deine wahre', titleAccent:'Sonnenzeit', subtitle:'Folge dem natürlichen Tagesrhythmus und plane deinen Flug zur besten Thermik.', solarTime:'SONNENZEIT', localTime:'Ortszeit', solarNoon:'SONNENMITTAG', ground:'stärkste Bodenerwärmung', thermal:'THERMIK-HÖHEPUNKT', air:'stärkste Lufterwärmung', distance:'1 SONNENMINUTE', along:'entlang dieses Breitengrads', location:'DEIN STANDORT', useLocation:'Meinen Standort nutzen', locating:'Standort wird ermittelt…', or:'ODER ORT EINGEBEN', placeholder:'z. B. Bassano del Grappa', search:'Suchen', searchHint:'Stadt, Region oder Adresse eingeben.', noResults:'Kein Ort gefunden.', errorSearch:'Ergebnisse konnten nicht geladen werden.', denied:'Standort nicht verfügbar. Bitte Ort eingeben.', select:'Ort auswählen', timezone:'Zeitzone', coords:'Koordinaten', info:'Die Zeiten sind Richtwerte. Thermik hängt auch von Wetter, Gelände und Jahreszeit ab.', footer:'Ortsdaten: © OpenStreetMap-Mitwirkende', km:'km', calculating:'Warte auf Standort' },
  es: { ...pl, tagline:'VUELA CON EL SOL', title:'Tu verdadera', titleAccent:'hora solar', subtitle:'Sigue el ritmo natural del día y vuela cuando la térmica está en su mejor momento.', solarTime:'HORA SOLAR', localTime:'hora local', solarNoon:'MEDIODÍA SOLAR', ground:'máximo calentamiento del suelo', thermal:'PICO TÉRMICO', air:'máximo calentamiento del aire', distance:'1 MINUTO SOLAR', along:'a lo largo de esta latitud', location:'TU UBICACIÓN', useLocation:'Usar mi ubicación', locating:'Localizando…', or:'O ESCRIBE UN LUGAR', placeholder:'p. ej. Bassano del Grappa', search:'Buscar', searchHint:'Introduce ciudad, región o dirección.', noResults:'No se encontró el lugar.', errorSearch:'No se pudieron cargar los resultados.', denied:'No se pudo obtener tu ubicación. Escríbela.', select:'Elige una ubicación', timezone:'Zona horaria', coords:'Coordenadas', info:'Las horas son orientativas. La térmica depende también del clima, terreno y estación.', footer:'Datos: © colaboradores de OpenStreetMap', km:'km', calculating:'Esperando ubicación' },
  it: { ...pl, tagline:'VOLA CON IL SOLE', title:'Il tuo vero', titleAccent:'tempo solare', subtitle:'Segui il ritmo naturale del giorno e vola quando la termica lavora al meglio.', solarTime:'TEMPO SOLARE', localTime:'ora locale', solarNoon:'MEZZOGIORNO SOLARE', ground:'massimo riscaldamento del suolo', thermal:'PICCO TERMICO', air:'massimo riscaldamento dell’aria', distance:'1 MINUTO SOLARE', along:'lungo questa latitudine', location:'LA TUA POSIZIONE', useLocation:'Usa la mia posizione', locating:'Localizzazione…', or:'OPPURE INSERISCI UN LUOGO', placeholder:'es. Bassano del Grappa', search:'Cerca', searchHint:'Inserisci città, regione o indirizzo.', noResults:'Luogo non trovato.', errorSearch:'Impossibile caricare i risultati.', denied:'Posizione non disponibile. Inserisci un luogo.', select:'Scegli una posizione', timezone:'Fuso orario', coords:'Coordinate', info:'Gli orari sono indicativi. La termica dipende anche da meteo, terreno e stagione.', footer:'Dati: © collaboratori OpenStreetMap', km:'km', calculating:'In attesa della posizione' },
  fr: { ...pl, tagline:'VOLE AVEC LE SOLEIL', title:'Ton véritable', titleAccent:'temps solaire', subtitle:'Suis le rythme naturel du jour et vole quand les thermiques sont les meilleurs.', solarTime:'TEMPS SOLAIRE', localTime:'heure locale', solarNoon:'MIDI SOLAIRE', ground:'réchauffement maximal du sol', thermal:'PIC THERMIQUE', air:'réchauffement maximal de l’air', distance:'1 MINUTE SOLAIRE', along:'le long de cette latitude', location:'TA POSITION', useLocation:'Utiliser ma position', locating:'Localisation…', or:'OU SAISIS UN LIEU', placeholder:'ex. Bassano del Grappa', search:'Rechercher', searchHint:'Saisis une ville, région ou adresse.', noResults:'Aucun lieu trouvé.', errorSearch:'Impossible de charger les résultats.', denied:'Position indisponible. Saisis un lieu.', select:'Choisir un lieu', timezone:'Fuseau horaire', coords:'Coordonnées', info:'Horaires indicatifs. Les thermiques dépendent aussi de la météo, du terrain et de la saison.', footer:'Données : © contributeurs OpenStreetMap', km:'km', calculating:'En attente de position' },
  uk: { ...pl, tagline:'ЛІТАЙ У РИТМІ СОНЦЯ', title:'Твій справжній', titleAccent:'сонячний час', subtitle:'Слідуй природному ритму дня та плануй політ, коли терміки найкращі.', solarTime:'СОНЯЧНИЙ ЧАС', localTime:'місцевий час', solarNoon:'СОНЯЧНИЙ ПОЛУДЕНЬ', ground:'найсильніше нагрівання землі', thermal:'ПІК ТЕРМІКІВ', air:'найсильніше нагрівання повітря', distance:'1 СОНЯЧНА ХВИЛИНА', along:'уздовж цієї широти', location:'ТВОЄ МІСЦЕ', useLocation:'Використати моє місце', locating:'Визначаю…', or:'АБО ВВЕДИ МІСЦЕ', placeholder:'напр. Bassano del Grappa', search:'Пошук', searchHint:'Введи місто, регіон або адресу.', noResults:'Місце не знайдено.', errorSearch:'Не вдалося завантажити результати.', denied:'Не вдалося визначити місце. Введи його.', select:'Обери місце', timezone:'Часовий пояс', coords:'Координати', info:'Час орієнтовний. Терміки також залежать від погоди, рельєфу та сезону.', footer:'Дані: © учасники OpenStreetMap', km:'км', calculating:'Очікую місце' },
  cs: { ...pl, tagline:'LEŤ V RYTMU SLUNCE', title:'Tvůj pravý', titleAccent:'sluneční čas', subtitle:'Sleduj přirozený rytmus dne a leť, když termika funguje nejlépe.', solarTime:'SLUNEČNÍ ČAS', localTime:'místní čas', solarNoon:'SLUNEČNÍ POLEDNE', ground:'nejsilnější ohřev země', thermal:'VRCHOL TERMIKY', air:'nejsilnější ohřev vzduchu', distance:'1 SLUNEČNÍ MINUTA', along:'podél této zeměpisné šířky', location:'TVOJE POLOHA', useLocation:'Použít moji polohu', locating:'Určuji polohu…', or:'NEBO ZADEJ MÍSTO', placeholder:'např. Bassano del Grappa', search:'Hledat', searchHint:'Zadej město, region nebo adresu.', noResults:'Místo nenalezeno.', errorSearch:'Výsledky se nepodařilo načíst.', denied:'Polohu nelze získat. Zadej místo.', select:'Vyber místo', timezone:'Časové pásmo', coords:'Souřadnice', info:'Časy jsou orientační. Termika závisí i na počasí, terénu a roční době.', footer:'Data: © přispěvatelé OpenStreetMap', km:'km', calculating:'Čekám na polohu' },
  sk: { ...pl, tagline:'LEŤ V RYTME SLNKA', title:'Tvoj pravý', titleAccent:'slnečný čas', subtitle:'Sleduj prirodzený rytmus dňa a leť, keď termika funguje najlepšie.', solarTime:'SLNEČNÝ ČAS', localTime:'miestny čas', solarNoon:'SLNEČNÉ POLUDNIE', ground:'najsilnejšie ohrievanie zeme', thermal:'VRCHOL TERMIKY', air:'najsilnejšie ohrievanie vzduchu', distance:'1 SLNEČNÁ MINÚTA', along:'pozdĺž tejto zemepisnej šírky', location:'TVOJA POLOHA', useLocation:'Použiť moju polohu', locating:'Určujem polohu…', or:'ALEBO ZADAJ MIESTO', placeholder:'napr. Bassano del Grappa', search:'Hľadať', searchHint:'Zadaj mesto, región alebo adresu.', noResults:'Miesto sa nenašlo.', errorSearch:'Výsledky sa nepodarilo načítať.', denied:'Polohu nemožno získať. Zadaj miesto.', select:'Vyber miesto', timezone:'Časové pásmo', coords:'Súradnice', info:'Časy sú orientačné. Termika závisí aj od počasia, terénu a ročného obdobia.', footer:'Dáta: © prispievatelia OpenStreetMap', km:'km', calculating:'Čakám na polohu' },
  hu: { ...pl, tagline:'REPÜLJ A NAPPAL', title:'A valódi', titleAccent:'napidőd', subtitle:'Kövesd a nap természetes ritmusát, és repülj, amikor a termik a legerősebb.', solarTime:'NAPIDŐ', localTime:'helyi idő', solarNoon:'DELELÉS', ground:'legerősebb talajmelegedés', thermal:'TERMIK CSÚCSA', air:'legerősebb levegőmelegedés', distance:'1 NAPPERC', along:'ezen a szélességi körön', location:'HELYZETED', useLocation:'Helyzetem használata', locating:'Helymeghatározás…', or:'VAGY ADJ MEG EGY HELYET', placeholder:'pl. Bassano del Grappa', search:'Keresés', searchHint:'Adj meg várost, régiót vagy címet.', noResults:'Nem található ilyen hely.', errorSearch:'Az eredmények nem tölthetők be.', denied:'A helyzet nem érhető el. Írj be egy helyet.', select:'Válassz helyet', timezone:'Időzóna', coords:'Koordináták', info:'Az időpontok tájékoztató jellegűek. A termik az időjárástól, tereptől és évszaktól is függ.', footer:'Helyadatok: © OpenStreetMap közreműködők', km:'km', calculating:'Helyzetre vár' }
}

export const getDictionary = (language: Language) => dictionaries[language]
